#!/usr/bin/env bash

source ./utils.bash

err $0 $#

path="$1"
ext="$2"

echo -e "\nSelect a script to run:"

PS3=$"
Press [ CTRL+C ] to exit
> "

cd "$path/"

select script in *.$ext
do

  case "$script" in
    *.$ext)
      echo Running $script...
      ./runner $script
      break
      ;;

    *)
      echo "Invalid option!"
      ;;
  esac

done

cd -
