#!/usr/bin/env bash

source ./utils.bash

err $0 $#

script_patterns=(
  output
  variables
  conditions

  switch

  numbers
  strings

  arrays
  key-values
  
  loops

  functions
  lambda
)

index=0

path=$1
ext=$2

mkdir -p "$path"

for script_name in ${script_patterns[*]}
do
  index=$(( $index + 1 ))
  script=$index'_'"$script_name.$ext"

  > "$path/$script"
done

echo '#!/usr/bin/env bash

script="$1"

# Edit the runner for that language
echo "$script"
' > "$path/runner"

chmod +x "$path/runner"

echo "Remember edit $path/runner"
